### ISSUE TITLE
Any examples or idea on how to add in plugins using your component?

### ISSUE THREAD

**Issue by mb-3000** [medmain/react-openseadragon#1]
Hi there,

I came across this plugin today and have been using it in a prototype and its really good!

I was wondering how you would go about adding in extra plugins to open seadragon using your component?  
I was interested in adding in https://github.com/picturae/openseadragonselection to my version and being new to react was wondering the best way to do it? I know I could probably import in a CDN version of the JS or my own if I downloaded it but how to add it into the prototype of your components OpenSeadragon instance as per their instructions in the plugin?

Thanks in Advance!

**Comment by mvila** [comment]
Hi @mb-3000,

The problem is that once you entered into the React world, you'll probably have to build everything inside it. So the OpenSeadragon plugin API might not be a good fit, and I'd recommend to build React components that connect to the React OpenSeadragon component through its `instance` property.

Unfortunately, I don't have any exemple of such components right now.

Good luck!

**Comment by mb-3000** [comment]
yeah I thought I might have to decorate it or something, by adding in the libraries and importing them in.

It's a really cool system, openseadragon, and its not needed today, the plugins, so I'll see how best to do it over the coming months.

Thanks again.
